import Joi = require("joi");
export declare const adminFirstNameSchema: Joi.StringSchema;
export declare const adminLastNameSchema: Joi.StringSchema;
export declare const adminEmailSchema: Joi.StringSchema;
export declare const adminPhoneSchema: Joi.StringSchema;
export declare const adminPasswordSchema: Joi.StringSchema;
export declare const adminRoleSchema: Joi.StringSchema;
export declare const isActiveSchema: Joi.BooleanSchema;
export declare const accountSchema: Joi.ObjectSchema<any>;
export declare const adminQuerySchema: Joi.ObjectSchema<any>;
