import Joi = require("joi");
export declare const adminFirstNameSchema: Joi.StringSchema;
export declare const adminLastNameSchema: Joi.StringSchema;
export declare const adminEmailSchema: Joi.StringSchema;
export declare const adminPhoneSchema: Joi.StringSchema;
export declare const adminPasswordSchema: Joi.StringSchema;
export declare const adminRoleSchema: Joi.NumberSchema;
export declare const isActiveSchema: Joi.BooleanSchema;
export declare const adminDeviceSchema: Joi.StringSchema;
export declare const adminCountrySchema: Joi.StringSchema;
export declare const adminCitySchema: Joi.StringSchema;
export declare const adminPlaceSchema: Joi.ObjectSchema<any>;
export declare const adminLastSessionSchema: Joi.ObjectSchema<any>;
export declare const adminSchema: Joi.ObjectSchema<any>;
export declare const adminQuerySchema: Joi.ObjectSchema<any>;
