import * as Joi from "joi";
export declare const chatTypeSchema: Joi.NumberSchema;
export declare const chatNameSchema: Joi.StringSchema;
export declare const messageTypeSchema: Joi.NumberSchema;
export declare const messageTextSchema: Joi.StringSchema;
export declare const starredMessageScheme: Joi.ObjectSchema<any>;
export declare const messageSchema: Joi.ObjectSchema<any>;
export declare const messagesSchema: Joi.ArraySchema;
export declare const chatSchema: Joi.ObjectSchema<any>;
export declare const chatsSchema: Joi.ArraySchema;
