import * as Joi from "joi";
export declare const chatTypeSchema: Joi.NumberSchema;
export declare const chatNameSchema: Joi.StringSchema;
export declare const messageTypeSchema: Joi.StringSchema;
export declare const messageSenderStatusSchema: Joi.StringSchema;
export declare const messageTextSchema: Joi.StringSchema;
export declare const messageSchema: Joi.ObjectSchema<any>;
export declare const messageForGetSchema: Joi.ObjectSchema<any>;
export declare const messagesForGetSchema: Joi.ArraySchema;
export declare const messagesSchema: Joi.ArraySchema;
export declare const messagesForGetWithCountSchema: Joi.ObjectSchema<any>;
export declare const chatSchema: Joi.ObjectSchema<any>;
export declare const chatsSchema: Joi.ArraySchema;
