import * as Joi from "joi";
export declare const contractAddressSchema: Joi.StringSchema;
export declare const contractAmountSchema: Joi.NumberSchema;
export declare const contractSymbolSchema: Joi.StringSchema;
export declare const contractTimestampSchema: Joi.DateSchema;
export declare const tokenOfPairSchema: Joi.ObjectSchema<any>;
export declare const contractPairSchema: Joi.ObjectSchema<any>;
export declare const liquiditySwapSchema: Joi.ObjectSchema<any>;
export declare const swapWQTSchema: Joi.ArraySchema;
export declare const contractTokenDay: Joi.ObjectSchema<any>;
export declare const tokensDayWQTSchema: Joi.ArraySchema;
