import * as Joi from "joi";
export declare const proposalNumberSchema: Joi.NumberSchema;
export declare const proposalTitleSchema: Joi.StringSchema;
export declare const proposalDescriptionSchema: Joi.StringSchema;
export declare const proposalStatus: Joi.NumberSchema;
export declare const proposerIdWalletSchema: Joi.StringSchema;
export declare const proposerVotingPeriodSchema: Joi.StringSchema;
export declare const proposalTimestampSchema: Joi.DateSchema;
export declare const nonceIdSchema: Joi.StringSchema;
export declare const proposalSchema: Joi.ObjectSchema<any>;
export declare const proposalEventSchema: Joi.ObjectSchema<any>;
export declare const allProposalsDataSchema: Joi.ArraySchema;
export declare const allProposalsSchema: Joi.ObjectSchema<any>;
