import * as Joi from "joi";
export declare const industryKeySchema: Joi.StringSchema;
export declare const industryNameSchema: Joi.StringSchema;
export declare const specializationKeySchema: Joi.StringSchema;
export declare const specializationNameSchema: Joi.StringSchema;
export declare const modelSpecializationSchema: Joi.ObjectSchema<any>;
export declare const specializationFilerSchema: Joi.AlternativesSchema;
export declare const industryKeysSchema: Joi.ArraySchema;
export declare const specializationKeysSchema: Joi.ArraySchema;
export declare const specializationsFilerSchema: Joi.ArraySchema;
export declare const modelSpecializationsSchema: Joi.ArraySchema;
export declare const specialisationsSchema: Joi.ObjectSchema<any>;
export declare const industryWithSpecialisationSchema: Joi.ObjectSchema<any>;
export declare const filterSchema: Joi.ObjectSchema<any>;
