"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.specializationsFilerSchema = exports.specializationFilerSchema = exports.specializationsSchema = exports.industriesSchema = exports.specializationSchema = exports.industrySchema = void 0;
const Joi = require("joi");
exports.industrySchema = Joi.string().pattern(/\d+/).example('1').label("Industry");
exports.specializationSchema = Joi.string().pattern(/\d+.\d+/).example('1.501').label('Specialization');
exports.industriesSchema = Joi.array().items(exports.industrySchema).label('Industries');
exports.specializationsSchema = Joi.array().items(exports.specializationSchema).label('Specializations');
exports.specializationFilerSchema = Joi.alternatives().try(exports.industrySchema, exports.specializationSchema).label('SpecializationFiler');
exports.specializationsFilerSchema = Joi.array().items(exports.specializationFilerSchema).label('SpecializationFiler');
