import * as Joi from "joi";
export declare const statisticAverageMark: Joi.NumberSchema;
export declare const chatsStatisticTypeSchema: Joi.StringSchema;
export declare const chatsStatisticSchema: Joi.ObjectSchema<any>;
export declare const questsStatisticSchema: Joi.ObjectSchema<any>;
export declare const userRatingStatusSchema: Joi.NumberSchema;
export declare const userRatingStatusesSchema: Joi.ArraySchema;
export declare const userRatingStatisticSchema: Joi.ObjectSchema<any>;
export declare const userStatisticsSchema: Joi.ObjectSchema<any>;
export declare const adminQuestDisputesStatisticSchema: Joi.ObjectSchema<any>;
