import * as Joi from "joi";
export declare const chatStatisticUnreadCountMessagesSchema: Joi.NumberSchema;
export declare const chatsStatisticSchema: Joi.ObjectSchema<any>;
export declare const completedSchema: Joi.NumberSchema;
export declare const openedSchema: Joi.NumberSchema;
export declare const questsStatisticSchema: Joi.ObjectSchema<any>;
export declare const ratingStatisticReviewCountSchema: Joi.NumberSchema;
export declare const ratingStatisticAverageMarkSchema: Joi.NumberSchema;
export declare const ratingStatusSchema: Joi.StringSchema;
export declare const ratingStatisticSchema: Joi.ObjectSchema<any>;
export declare const userStatisticsSchema: Joi.ObjectSchema<any>;
