import * as Joi from "joi";
export declare const statisticAverageMark: Joi.NumberSchema;
export declare const chatsStatisticTypeSchema: Joi.StringSchema;
export declare const adminChatsStatisticSchema: Joi.ObjectSchema<any>;
export declare const userChatsStatisticSchema: Joi.ObjectSchema<any>;
export declare const questsStatisticSchema: Joi.ObjectSchema<any>;
export declare const userRatingStatusSchema: Joi.NumberSchema;
export declare const userRatingStatusesSchema: Joi.ArraySchema;
export declare const userRatingStatisticSchema: Joi.ObjectSchema<any>;
export declare const userStatisticsSchema: Joi.ObjectSchema<any>;
export declare const adminQuestDisputesStatisticSchema: Joi.ObjectSchema<any>;
export declare const disputeDecideStatisticSchema: Joi.ObjectSchema<any>;
export declare const reportEntityStatisticSchema: Joi.ObjectSchema<any>;
export declare const reportStatisticSchema: Joi.ObjectSchema<any>;
export declare const adminDisputeStatisticSchema: Joi.ObjectSchema<any>;
export declare const supportStatisticSchema: Joi.ObjectSchema<any>;
