import * as Joi from "joi";
export declare const numberSupportTicketSchema: Joi.NumberSchema;
export declare const titleSupportTicketSchema: Joi.StringSchema;
export declare const descriptionSupportTicketSchema: Joi.StringSchema;
export declare const statusSupportTicketSchema: Joi.NumberSchema;
export declare const postedDecisionSupportTicketSchema: Joi.StringSchema;
export declare const supportTicketSchema: Joi.ObjectSchema<any>;
export declare const supportOnlyTicketSchema: Joi.ObjectSchema<any>;
export declare const supportTicketQuerySchema: Joi.ObjectSchema<any>;
export declare const supportTicketsForGetSchema: Joi.ArraySchema;
