"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.usersPlatformStatisticFieldsArray = exports.reportsPlatformStatisticFieldsArray = exports.raiseViewsPlatformStatisticFieldsArray = exports.questsPlatformStatisticFieldsArray = exports.disputesPlatformStatisticFieldsArray = exports.daoPlatformStatisticFieldsArray = exports.UsersPlatformStatisticFields = exports.ReportsPlatformStatisticFields = exports.RaiseViewsPlatformStatisticFields = exports.QuestsPlatformStatisticFields = exports.DisputesPlatformStatisticFields = exports.DaoPlatformStatisticFields = void 0;
var DaoPlatformStatisticFields;
(function (DaoPlatformStatisticFields) {
    DaoPlatformStatisticFields["Votes"] = "votes";
    DaoPlatformStatisticFields["DelegatedValue"] = "delegatedValue";
    DaoPlatformStatisticFields["VotesForPercent"] = "votesForPercent";
    DaoPlatformStatisticFields["VotesAgainPercent"] = "votesAgainPercent";
})(DaoPlatformStatisticFields = exports.DaoPlatformStatisticFields || (exports.DaoPlatformStatisticFields = {}));
var DisputesPlatformStatisticFields;
(function (DisputesPlatformStatisticFields) {
    DisputesPlatformStatisticFields["Total"] = "total";
    DisputesPlatformStatisticFields["Pending"] = "pending";
    DisputesPlatformStatisticFields["Created"] = "created";
    DisputesPlatformStatisticFields["InProgress"] = "inProgress";
    DisputesPlatformStatisticFields["AcceptedWork"] = "acceptedWork";
})(DisputesPlatformStatisticFields = exports.DisputesPlatformStatisticFields || (exports.DisputesPlatformStatisticFields = {}));
var QuestsPlatformStatisticFields;
(function (QuestsPlatformStatisticFields) {
    QuestsPlatformStatisticFields["Total"] = "total";
    QuestsPlatformStatisticFields["Closed"] = "closed";
    QuestsPlatformStatisticFields["Dispute"] = "dispute";
    QuestsPlatformStatisticFields["Blocked"] = "blocked";
    QuestsPlatformStatisticFields["Pending"] = "pending";
    QuestsPlatformStatisticFields["Recruitment"] = "recruitment";
    QuestsPlatformStatisticFields["WaitingForConfirmFromWorkerOnAssign"] = "waitingForConfirmFromWorkerOnAssign";
    QuestsPlatformStatisticFields["ExecutionOfWork"] = "executionOfWork";
    QuestsPlatformStatisticFields["WaitingForEmployerConfirmationWork"] = "waitingForEmployerConfirmationWork";
    QuestsPlatformStatisticFields["Completed"] = "completed";
})(QuestsPlatformStatisticFields = exports.QuestsPlatformStatisticFields || (exports.QuestsPlatformStatisticFields = {}));
var RaiseViewsPlatformStatisticFields;
(function (RaiseViewsPlatformStatisticFields) {
    RaiseViewsPlatformStatisticFields["ProfilesTotal"] = "profilesTotal";
    RaiseViewsPlatformStatisticFields["ProfilesGoldPlus"] = "profilesGoldPlus";
    RaiseViewsPlatformStatisticFields["ProfilesGold"] = "profilesGold";
    RaiseViewsPlatformStatisticFields["ProfilesSilver"] = "profilesSilver";
    RaiseViewsPlatformStatisticFields["ProfilesBronze"] = "profilesBronze";
    RaiseViewsPlatformStatisticFields["QuestsTotal"] = "questsTotal";
    RaiseViewsPlatformStatisticFields["QuestsGoldPlus"] = "questsGoldPlus";
    RaiseViewsPlatformStatisticFields["QuestsGold"] = "questsGold";
    RaiseViewsPlatformStatisticFields["QuestsSilver"] = "questsSilver";
    RaiseViewsPlatformStatisticFields["QuestsBronze"] = "questsBronze";
})(RaiseViewsPlatformStatisticFields = exports.RaiseViewsPlatformStatisticFields || (exports.RaiseViewsPlatformStatisticFields = {}));
var ReportsPlatformStatisticFields;
(function (ReportsPlatformStatisticFields) {
    ReportsPlatformStatisticFields["Users"] = "users";
    ReportsPlatformStatisticFields["DeclinedUsers"] = "declinedUsers";
    ReportsPlatformStatisticFields["DecidedUsers"] = "decidedUsers";
    ReportsPlatformStatisticFields["Quests"] = "quests";
    ReportsPlatformStatisticFields["DeclinedQuests"] = "declinedQuests";
    ReportsPlatformStatisticFields["DecidedQuests"] = "decidedQuests";
})(ReportsPlatformStatisticFields = exports.ReportsPlatformStatisticFields || (exports.ReportsPlatformStatisticFields = {}));
var UsersPlatformStatisticFields;
(function (UsersPlatformStatisticFields) {
    UsersPlatformStatisticFields["Registered"] = "registered";
    UsersPlatformStatisticFields["Finished"] = "finished";
    UsersPlatformStatisticFields["Unfinished"] = "unfinished";
    UsersPlatformStatisticFields["Workers"] = "workers";
    UsersPlatformStatisticFields["Employers"] = "employers";
    UsersPlatformStatisticFields["Linkedin"] = "linkedin";
    UsersPlatformStatisticFields["Twitter"] = "twitter";
    UsersPlatformStatisticFields["Facebook"] = "facebook";
    UsersPlatformStatisticFields["Google"] = "google";
    UsersPlatformStatisticFields["SmsPassed"] = "smsPassed";
    UsersPlatformStatisticFields["SmsNotPassed"] = "smsNotPassed";
    UsersPlatformStatisticFields["KycPassed"] = "kycPassed";
    UsersPlatformStatisticFields["KycNotPassed"] = "kycNotPassed";
    UsersPlatformStatisticFields["UseWeb"] = "useWeb";
    UsersPlatformStatisticFields["UseApp"] = "useApp";
    UsersPlatformStatisticFields["UseWallet"] = "useWallet";
    UsersPlatformStatisticFields["Use2FA"] = "use2FA";
})(UsersPlatformStatisticFields = exports.UsersPlatformStatisticFields || (exports.UsersPlatformStatisticFields = {}));
exports.daoPlatformStatisticFieldsArray = Object.values(DaoPlatformStatisticFields);
exports.disputesPlatformStatisticFieldsArray = Object.values(DisputesPlatformStatisticFields);
exports.questsPlatformStatisticFieldsArray = Object.values(QuestsPlatformStatisticFields);
exports.raiseViewsPlatformStatisticFieldsArray = Object.values(RaiseViewsPlatformStatisticFields);
exports.reportsPlatformStatisticFieldsArray = Object.values(ReportsPlatformStatisticFields);
exports.usersPlatformStatisticFieldsArray = Object.values(UsersPlatformStatisticFields);
